[package]
name = "dla"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
hashbrown = "0.14"
rand = "0.8"

[dev-dependencies]
proptest = "1.0"
