[package]
name = "dla"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
hashbrown = "0.12"
rand = "0.8"

[dev-dependencies]
proptest = "1.0"
